name: Workflow de Disparo Manual

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm install

    - name: Rodar os testes de API 
      run: npm test

    - name: Subir a API Rest 
      run: 
        npm start &
        npx wait-on tcp:3000 --timeout 60000

    - name: Esperar as APIs estarem Funcionando
      run: sleep 8

    - name: Criar .env
      run: |
        echo "BASE_URL_REST=${{ secrets.BASE_URL}}" >> .env


    - name: Rodar os testes  de API Rest via HTTP
      run: npm test

