name: CI - Testes

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      BASE_URL: 'http://localhost:3000'
      NODE_ENV: 'test'

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v6

      - name: Instalar dependências
        run: npm ci

      - name: Instalar wait-on
        run: npm install --save-dev wait-on

      - name: Iniciar servidor e aguardar
        run: |
          npm start &
          npx wait-on http://localhost:3000

      - name: Executar testes
        run: npm test
