name: CI - Testes

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      BASE_URL: 'http://localhost:3000'
      NODE_ENV: 'test'

    steps:
      # Clonar o repositório
      - name: Checkout do repositório
        uses: actions/checkout@v6

      # Instalar dependências
      - name: Instalar dependências
        run: npm ci       

      # Iniciar servidor de aplicação em background
      - name: Iniciar servidor de aplicação
        run: npm start &

      # Esperar o servidor estar pronto
      - name: Aguardar servidor
        run: |
          echo "Aguardando servidor..."
          npx wait-on http://localhost:3000

      # Executar os testes
      - name: Executar testes
        run: npm test
